apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jenkins-chart.fullname" . }}-secret
  labels:
    {{- include "jenkins-chart.labels" . | nindent 4 }}
type: Opaque
data:
  jenkins-admin-user: {{ .Values.jenkins.admin.username | b64enc | quote }}
  jenkins-admin-password: {{ .Values.jenkins.admin.password | b64enc | quote }}
  {{- if .Values.database.external.enabled }}
  database-username: {{ .Values.database.external.username | b64enc | quote }}
  database-password: {{ .Values.database.external.password | b64enc | quote }}
  {{- end }}
