apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkins-chart.fullname" . }}-service
  labels:
    {{- include "jenkins-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.jenkins.service.type }}
  ports:
  - port: {{ .Values.jenkins.service.port }}
    targetPort: {{ .Values.jenkins.service.targetPort }}
    protocol: TCP
    name: http
  - port: 50000
    targetPort: 50000
    protocol: TCP
    name: jnlp
  selector:
    {{- include "jenkins-chart.selectorLabels" . | nindent 4 }}
