# templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sonarqube-secret
  namespace: {{ .Values.sonarqube.namespace }}
  labels:
    app.kubernetes.io/name: sonarqube
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  admin-username: {{ .Values.sonarqube.admin.username | b64enc }}
  admin-password: {{ .Values.sonarqube.admin.password | b64enc }}
  {{- if .Values.sonarqube.database.external }}
  db-username: {{ .Values.sonarqube.database.username | b64enc }}
  db-password: {{ .Values.sonarqube.database.password | b64enc }}
  {{- else }}
  db-username: {{ .Values.sonarqube.database.postgresql.username | b64enc }}
  db-password: {{ .Values.sonarqube.database.postgresql.password | b64enc }}
  {{- end }}
