# templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: {{ .Values.argocd.namespace }}
type: Opaque
data:
  admin-password: {{ .Values.argocd.admin.password | b64enc }}
