# Chart.yaml - Updated
apiVersion: v2
name: nexus-chart
description: A Helm chart for Nexus Repository Manager with custom configuration
type: application
version: 0.2.0  # Increment version
appVersion: "3.68.1"  # Updated to secure version
keywords:
  - nexus
  - repository
  - artifacts
  - devops
home: https://www.sonatype.com/nexus/repository-oss
sources:
  - https://github.com/sonatype/nexus-public
maintainers:
  - name: DevOps Team
    email: devops@cprime.com
